/*
 * Copyright (c) 2026 Microchip Technology Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file mchp_pic32ck_sg_gc_clock.h
 * @brief List clock subsystem IDs for pic32ck_sg_gc family.
 *
 * Clock subsystem IDs. To be used in devicetree nodes, and as argument for clock API.
 */

#ifndef INCLUDE_ZEPHYR_DT_BINDINGS_CLOCK_MCHP_PIC32CK_SG_GC_CLOCK_H_
#define INCLUDE_ZEPHYR_DT_BINDINGS_CLOCK_MCHP_PIC32CK_SG_GC_CLOCK_H_

/**
 * Encode clock type, mclk bus, mclk mask bit, gclk pch and instance number,
 * to clock subsystem.
 *
 * - 00..07 (8 bits): inst
 *
 * - 08..13 (6 bits): gclkperiph
 * (values from 0 to 47)
 *
 * - 14..19 (6 bits): mclkmaskbit
 * (values from 0 to 31)
 *
 * - 20..25 (6 bits): mclkmaskreg
 * following values
 * MCLKMSK0 (0)
 * MCLKMSK1 (1)
 * MCLKMSK2 (2)
 *
 * - 26..31 (6 bits): type
 * following values
 * SUBSYS_TYPE_XOSC       (0)
 * SUBSYS_TYPE_DFLL48M    (1)
 * SUBSYS_TYPE_PLL       (2)
 * SUBSYS_TYPE_PLL_OUT   (3)
 * SUBSYS_TYPE_RTC        (4)
 * SUBSYS_TYPE_XOSC32K    (5)
 * SUBSYS_TYPE_GCLKGEN    (6)
 * SUBSYS_TYPE_GCLKPERIPH (7)
 * SUBSYS_TYPE_MCLKDOMAIN (8)
 * SUBSYS_TYPE_MCLKPERIPH (9)
 *
 * @param type clock subsystem type
 * @param mclkmaskreg select from the AHBx and the APBx buses
 * @param mclkmaskbit select the module connected to AHBx or APBx bus (0 to 31)
 * @param gclkperiph gclk peripheral channel number m in PCHTRLm (0 to 63)
 * @param inst instance number of the specified clock type
 */
#define MCHP_CLOCK_DERIVE_ID(type, mclkmaskreg, mclkmaskbit, gclkperiph, inst)                     \
	(((type) << 26) | ((mclkmaskreg) << 20) | ((mclkmaskbit) << 14) | ((gclkperiph) << 8) |    \
	 inst)

/* XOSC_TYPE ids */
#define CLOCK_MCHP_XOSC_ID     MCHP_CLOCK_DERIVE_ID(0, 0x3f, 0x3f, 0x3f, 0)
#define CLOCK_MCHP_XOSC_ID_MAX (0)

/* DFLL48M_TYPE ids */
#define CLOCK_MCHP_DFLL48M_ID     MCHP_CLOCK_DERIVE_ID(1, 0x3f, 0x3f, 0, 0)
#define CLOCK_MCHP_DFLL48M_ID_MAX (0)

/* PLL_TYPE ids */
#define CLOCK_MCHP_PLL_ID_PLL0 MCHP_CLOCK_DERIVE_ID(2, 0x3f, 0x3f, 0, 0)
#define CLOCK_MCHP_PLL_ID_MAX  (0)

/* PLL0_OUT_TYPE ids */
#define CLOCK_MCHP_PLL0_ID_OUT0    MCHP_CLOCK_DERIVE_ID(3, 0x3f, 0x3f, 0x3f, 0)
#define CLOCK_MCHP_PLL0_ID_OUT1    MCHP_CLOCK_DERIVE_ID(3, 0x3f, 0x3f, 0x3f, 1)
#define CLOCK_MCHP_PLL0_ID_OUT2    MCHP_CLOCK_DERIVE_ID(3, 0x3f, 0x3f, 0x3f, 2)
#define CLOCK_MCHP_PLL0_ID_OUT3    MCHP_CLOCK_DERIVE_ID(3, 0x3f, 0x3f, 0x3f, 3)
#define CLOCK_MCHP_PLL0_ID_OUT4    MCHP_CLOCK_DERIVE_ID(3, 0x3f, 0x3f, 0x3f, 4)
#define CLOCK_MCHP_PLL0_ID_OUT5    MCHP_CLOCK_DERIVE_ID(3, 0x3f, 0x3f, 0x3f, 5)
#define CLOCK_MCHP_PLL0_OUT_ID_MAX (5)

/* RTC_TYPE ids */
#define CLOCK_MCHP_RTC_ID     MCHP_CLOCK_DERIVE_ID(4, 0x3f, 0x3f, 0x3f, 0)
#define CLOCK_MCHP_RTC_ID_MAX (0)

/* XOSC32K_TYPE ids */
#define CLOCK_MCHP_XOSC32K_ID     MCHP_CLOCK_DERIVE_ID(5, 0x3f, 0x3f, 0x3f, 0)
#define CLOCK_MCHP_XOSC32K_ID_MAX (0)

/* GCLKGEN_TYPE ids */
#define CLOCK_MCHP_GCLKGEN_ID_GEN0  MCHP_CLOCK_DERIVE_ID(6, 0x3f, 0x3f, 0x3f, 0)
#define CLOCK_MCHP_GCLKGEN_ID_GEN1  MCHP_CLOCK_DERIVE_ID(6, 0x3f, 0x3f, 0x3f, 1)
#define CLOCK_MCHP_GCLKGEN_ID_GEN2  MCHP_CLOCK_DERIVE_ID(6, 0x3f, 0x3f, 0x3f, 2)
#define CLOCK_MCHP_GCLKGEN_ID_GEN3  MCHP_CLOCK_DERIVE_ID(6, 0x3f, 0x3f, 0x3f, 3)
#define CLOCK_MCHP_GCLKGEN_ID_GEN4  MCHP_CLOCK_DERIVE_ID(6, 0x3f, 0x3f, 0x3f, 4)
#define CLOCK_MCHP_GCLKGEN_ID_GEN5  MCHP_CLOCK_DERIVE_ID(6, 0x3f, 0x3f, 0x3f, 5)
#define CLOCK_MCHP_GCLKGEN_ID_GEN6  MCHP_CLOCK_DERIVE_ID(6, 0x3f, 0x3f, 0x3f, 6)
#define CLOCK_MCHP_GCLKGEN_ID_GEN7  MCHP_CLOCK_DERIVE_ID(6, 0x3f, 0x3f, 0x3f, 7)
#define CLOCK_MCHP_GCLKGEN_ID_GEN8  MCHP_CLOCK_DERIVE_ID(6, 0x3f, 0x3f, 0x3f, 8)
#define CLOCK_MCHP_GCLKGEN_ID_GEN9  MCHP_CLOCK_DERIVE_ID(6, 0x3f, 0x3f, 0x3f, 9)
#define CLOCK_MCHP_GCLKGEN_ID_GEN10 MCHP_CLOCK_DERIVE_ID(6, 0x3f, 0x3f, 0x3f, 10)
#define CLOCK_MCHP_GCLKGEN_ID_GEN11 MCHP_CLOCK_DERIVE_ID(6, 0x3f, 0x3f, 0x3f, 11)
#define CLOCK_MCHP_GCLKGEN_ID_MAX   (11)

/* GCLKPERIPH_TYPE ids */
#define CLOCK_MCHP_GCLKPERIPH_ID_FREQM_MSR0   MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 2, 0)
#define CLOCK_MCHP_GCLKPERIPH_ID_FREQM_MSR1   MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 3, 1)
#define CLOCK_MCHP_GCLKPERIPH_ID_FREQM_REF    MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 4, 2)
#define CLOCK_MCHP_GCLKPERIPH_ID_EIC          MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 5, 3)
#define CLOCK_MCHP_GCLKPERIPH_ID_EVSYS_CH0    MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 6, 4)
#define CLOCK_MCHP_GCLKPERIPH_ID_EVSYS_CH1    MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 7, 5)
#define CLOCK_MCHP_GCLKPERIPH_ID_EVSYS_CH2    MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 8, 6)
#define CLOCK_MCHP_GCLKPERIPH_ID_EVSYS_CH3    MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 9, 7)
#define CLOCK_MCHP_GCLKPERIPH_ID_EVSYS_CH4    MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 10, 8)
#define CLOCK_MCHP_GCLKPERIPH_ID_EVSYS_CH5    MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 11, 9)
#define CLOCK_MCHP_GCLKPERIPH_ID_EVSYS_CH6    MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 12, 10)
#define CLOCK_MCHP_GCLKPERIPH_ID_EVSYS_CH7    MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 13, 11)
#define CLOCK_MCHP_GCLKPERIPH_ID_EVSYS_CH8    MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 14, 12)
#define CLOCK_MCHP_GCLKPERIPH_ID_EVSYS_CH9    MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 15, 13)
#define CLOCK_MCHP_GCLKPERIPH_ID_EVSYS_CH10   MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 16, 14)
#define CLOCK_MCHP_GCLKPERIPH_ID_EVSYS_CH11   MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 17, 15)
#define CLOCK_MCHP_GCLKPERIPH_ID_SDMMC0_SLOW  MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 18, 16)
#define CLOCK_MCHP_GCLKPERIPH_ID_SDMMC1_SLOW  MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 18, 17)
#define CLOCK_MCHP_GCLKPERIPH_ID_SERCOM0_SLOW MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 18, 18)
#define CLOCK_MCHP_GCLKPERIPH_ID_SERCOM1_SLOW MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 18, 19)
#define CLOCK_MCHP_GCLKPERIPH_ID_SERCOM4_SLOW MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 18, 20)
#define CLOCK_MCHP_GCLKPERIPH_ID_SERCOM2_SLOW MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 18, 21)
#define CLOCK_MCHP_GCLKPERIPH_ID_SERCOM3_SLOW MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 18, 22)
#define CLOCK_MCHP_GCLKPERIPH_ID_SERCOM5_SLOW MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 18, 23)
#define CLOCK_MCHP_GCLKPERIPH_ID_SERCOM6_SLOW MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 18, 24)
#define CLOCK_MCHP_GCLKPERIPH_ID_SERCOM7_SLOW MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 18, 25)
#define CLOCK_MCHP_GCLKPERIPH_ID_SERCOM0_CORE MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 19, 26)
#define CLOCK_MCHP_GCLKPERIPH_ID_SERCOM1_CORE MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 20, 27)
#define CLOCK_MCHP_GCLKPERIPH_ID_SERCOM2_CORE MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 21, 28)
#define CLOCK_MCHP_GCLKPERIPH_ID_SERCOM3_CORE MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 22, 29)
#define CLOCK_MCHP_GCLKPERIPH_ID_TCC0         MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 23, 30)
#define CLOCK_MCHP_GCLKPERIPH_ID_TCC1         MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 23, 31)
#define CLOCK_MCHP_GCLKPERIPH_ID_TCC2         MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 24, 32)
#define CLOCK_MCHP_GCLKPERIPH_ID_TCC3         MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 24, 33)
#define CLOCK_MCHP_GCLKPERIPH_ID_SERCOM4_CORE MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 25, 34)
#define CLOCK_MCHP_GCLKPERIPH_ID_SERCOM5_CORE MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 26, 35)
#define CLOCK_MCHP_GCLKPERIPH_ID_SERCOM6_CORE MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 27, 36)
#define CLOCK_MCHP_GCLKPERIPH_ID_SERCOM7_CORE MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 28, 37)
#define CLOCK_MCHP_GCLKPERIPH_ID_TCC4         MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 29, 38)
#define CLOCK_MCHP_GCLKPERIPH_ID_TCC5         MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 30, 39)
#define CLOCK_MCHP_GCLKPERIPH_ID_TCC6         MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 31, 40)
#define CLOCK_MCHP_GCLKPERIPH_ID_TCC7         MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 32, 41)
#define CLOCK_MCHP_GCLKPERIPH_ID_ADC          MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 33, 42)
#define CLOCK_MCHP_GCLKPERIPH_ID_AC           MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 34, 43)
#define CLOCK_MCHP_GCLKPERIPH_ID_PTC          MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 35, 44)
#define CLOCK_MCHP_GCLKPERIPH_ID_SPI_IXS      MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 36, 45)
#define CLOCK_MCHP_GCLKPERIPH_ID_CCL          MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 37, 46)
#define CLOCK_MCHP_GCLKPERIPH_ID_PDEC         MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 38, 47)
#define CLOCK_MCHP_GCLKPERIPH_ID_CAN0         MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 39, 48)
#define CLOCK_MCHP_GCLKPERIPH_ID_CAN1         MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 40, 49)
#define CLOCK_MCHP_GCLKPERIPH_ID_ETH_TX       MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 41, 50)
#define CLOCK_MCHP_GCLKPERIPH_ID_ETH_TSU      MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 42, 51)
#define CLOCK_MCHP_GCLKPERIPH_ID_SQI          MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 43, 52)
#define CLOCK_MCHP_GCLKPERIPH_ID_SDMMC0       MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 44, 53)
#define CLOCK_MCHP_GCLKPERIPH_ID_SDMMC1       MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 45, 54)
#define CLOCK_MCHP_GCLKPERIPH_ID_USB          MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 48, 55)
#define CLOCK_MCHP_GCLKPERIPH_ID_CPU0_TRACE   MCHP_CLOCK_DERIVE_ID(7, 0x3f, 0x3f, 47, 56)
#define CLOCK_MCHP_GCLKPERIPH_ID_MAX          (56)

/* MCLKDOMAIN_TYPE ids */
#define CLOCK_MCHP_MCLKCPU_ID  MCHP_CLOCK_DERIVE_ID(8, 0x3f, 0x3f, 0x3f, 0)
#define CLOCK_MCHP_MCLKCPU_MAX (0)

/* MCLKPERIPH_TYPE ids */
#define CLOCK_MCHP_MCLKPERIPH_ID_DSU_AHB    MCHP_CLOCK_DERIVE_ID(9, 0, 3, 0x3f, 0)
#define CLOCK_MCHP_MCLKPERIPH_ID_FCR_AHB    MCHP_CLOCK_DERIVE_ID(9, 0, 4, 0x3f, 1)
#define CLOCK_MCHP_MCLKPERIPH_ID_FCW_AHB    MCHP_CLOCK_DERIVE_ID(9, 0, 5, 0x3f, 2)
#define CLOCK_MCHP_MCLKPERIPH_ID_PAC_AHB    MCHP_CLOCK_DERIVE_ID(9, 0, 6, 0x3f, 3)
#define CLOCK_MCHP_MCLKPERIPH_ID_DMA0_AHB   MCHP_CLOCK_DERIVE_ID(9, 0, 8, 0x3f, 4)
#define CLOCK_MCHP_MCLKPERIPH_ID_DMA1_AHB   MCHP_CLOCK_DERIVE_ID(9, 0, 9, 0x3f, 5)
#define CLOCK_MCHP_MCLKPERIPH_ID_PRM_AHB    MCHP_CLOCK_DERIVE_ID(9, 0, 12, 0x3f, 6)
#define CLOCK_MCHP_MCLKPERIPH_ID_CAN0_AHB   MCHP_CLOCK_DERIVE_ID(9, 0, 13, 0x3f, 7)
#define CLOCK_MCHP_MCLKPERIPH_ID_CAN1_AHB   MCHP_CLOCK_DERIVE_ID(9, 0, 14, 0x3f, 8)
#define CLOCK_MCHP_MCLKPERIPH_ID_ETH_AHB    MCHP_CLOCK_DERIVE_ID(9, 0, 15, 0x3f, 9)
#define CLOCK_MCHP_MCLKPERIPH_ID_SQI_AHB    MCHP_CLOCK_DERIVE_ID(9, 0, 16, 0x3f, 10)
#define CLOCK_MCHP_MCLKPERIPH_ID_SDMMC0_AHB MCHP_CLOCK_DERIVE_ID(9, 0, 17, 0x3f, 11)
#define CLOCK_MCHP_MCLKPERIPH_ID_SDMMC1_AHB MCHP_CLOCK_DERIVE_ID(9, 0, 18, 0x3f, 12)
#define CLOCK_MCHP_MCLKPERIPH_ID_USBFS_AHB  MCHP_CLOCK_DERIVE_ID(9, 0, 19, 0x3f, 13)
#define CLOCK_MCHP_MCLKPERIPH_ID_USBHS_AHB  MCHP_CLOCK_DERIVE_ID(9, 0, 20, 0x3f, 14)
#define CLOCK_MCHP_MCLKPERIPH_ID_EBI_AHB    MCHP_CLOCK_DERIVE_ID(9, 0, 21, 0x3f, 15)
#define CLOCK_MCHP_MCLKPERIPH_ID_HSM_AHB    MCHP_CLOCK_DERIVE_ID(9, 0, 22, 0x3f, 16)

#define CLOCK_MCHP_MCLKPERIPH_ID_DSU_APB        MCHP_CLOCK_DERIVE_ID(9, 1, 0, 0x3f, 17)
#define CLOCK_MCHP_MCLKPERIPH_ID_FCR_APB        MCHP_CLOCK_DERIVE_ID(9, 1, 1, 0x3f, 18)
#define CLOCK_MCHP_MCLKPERIPH_ID_FCW_APB        MCHP_CLOCK_DERIVE_ID(9, 1, 2, 0x3f, 19)
#define CLOCK_MCHP_MCLKPERIPH_ID_RSTC_APB       MCHP_CLOCK_DERIVE_ID(9, 1, 5, 0x3f, 20)
#define CLOCK_MCHP_MCLKPERIPH_ID_OSCCTRL_APB    MCHP_CLOCK_DERIVE_ID(9, 1, 6, 0x3f, 21)
#define CLOCK_MCHP_MCLKPERIPH_ID_OSC32KCTRL_APB MCHP_CLOCK_DERIVE_ID(9, 1, 7, 0x3f, 22)
#define CLOCK_MCHP_MCLKPERIPH_ID_FREQM_APB      MCHP_CLOCK_DERIVE_ID(9, 1, 10, 0x3f, 23)
#define CLOCK_MCHP_MCLKPERIPH_ID_WDT_APB        MCHP_CLOCK_DERIVE_ID(9, 1, 11, 0x3f, 24)
#define CLOCK_MCHP_MCLKPERIPH_ID_RTC_APB        MCHP_CLOCK_DERIVE_ID(9, 1, 12, 0x3f, 25)
#define CLOCK_MCHP_MCLKPERIPH_ID_EIC_APB        MCHP_CLOCK_DERIVE_ID(9, 1, 13, 0x3f, 26)
#define CLOCK_MCHP_MCLKPERIPH_ID_PAC_APB        MCHP_CLOCK_DERIVE_ID(9, 1, 14, 0x3f, 27)
#define CLOCK_MCHP_MCLKPERIPH_ID_TRAM_APB       MCHP_CLOCK_DERIVE_ID(9, 1, 15, 0x3f, 28)
#define CLOCK_MCHP_MCLKPERIPH_ID_MBISTINTF_APB  MCHP_CLOCK_DERIVE_ID(9, 1, 18, 0x3f, 29)
#define CLOCK_MCHP_MCLKPERIPH_ID_TDM_APB        MCHP_CLOCK_DERIVE_ID(9, 1, 19, 0x3f, 30)

#define CLOCK_MCHP_MCLKPERIPH_ID_PORT_APB    MCHP_CLOCK_DERIVE_ID(9, 2, 0, 0x3f, 31)
#define CLOCK_MCHP_MCLKPERIPH_ID_DMA0_APB    MCHP_CLOCK_DERIVE_ID(9, 2, 1, 0x3f, 32)
#define CLOCK_MCHP_MCLKPERIPH_ID_DMA1_APB    MCHP_CLOCK_DERIVE_ID(9, 2, 2, 0x3f, 33)
#define CLOCK_MCHP_MCLKPERIPH_ID_PRM_APB     MCHP_CLOCK_DERIVE_ID(9, 2, 4, 0x3f, 34)
#define CLOCK_MCHP_MCLKPERIPH_ID_IDAU_APB    MCHP_CLOCK_DERIVE_ID(9, 2, 5, 0x3f, 35)
#define CLOCK_MCHP_MCLKPERIPH_ID_EVSYS_APB   MCHP_CLOCK_DERIVE_ID(9, 2, 6, 0x3f, 36)
#define CLOCK_MCHP_MCLKPERIPH_ID_SERCOM0_APB MCHP_CLOCK_DERIVE_ID(9, 2, 7, 0x3f, 37)
#define CLOCK_MCHP_MCLKPERIPH_ID_SERCOM1_APB MCHP_CLOCK_DERIVE_ID(9, 2, 8, 0x3f, 38)
#define CLOCK_MCHP_MCLKPERIPH_ID_SERCOM2_APB MCHP_CLOCK_DERIVE_ID(9, 2, 9, 0x3f, 39)
#define CLOCK_MCHP_MCLKPERIPH_ID_SERCOM3_APB MCHP_CLOCK_DERIVE_ID(9, 2, 10, 0x3f, 40)
#define CLOCK_MCHP_MCLKPERIPH_ID_TCC0_APB    MCHP_CLOCK_DERIVE_ID(9, 2, 11, 0x3f, 41)
#define CLOCK_MCHP_MCLKPERIPH_ID_TCC1_APB    MCHP_CLOCK_DERIVE_ID(9, 2, 12, 0x3f, 42)
#define CLOCK_MCHP_MCLKPERIPH_ID_TCC2_APB    MCHP_CLOCK_DERIVE_ID(9, 2, 13, 0x3f, 43)
#define CLOCK_MCHP_MCLKPERIPH_ID_TCC3_APB    MCHP_CLOCK_DERIVE_ID(9, 2, 14, 0x3f, 44)

#define CLOCK_MCHP_MCLKPERIPH_ID_SERCOM4_APB MCHP_CLOCK_DERIVE_ID(9, 3, 0, 0x3f, 45)
#define CLOCK_MCHP_MCLKPERIPH_ID_SERCOM5_APB MCHP_CLOCK_DERIVE_ID(9, 3, 1, 0x3f, 46)
#define CLOCK_MCHP_MCLKPERIPH_ID_SERCOM6_APB MCHP_CLOCK_DERIVE_ID(9, 3, 2, 0x3f, 47)
#define CLOCK_MCHP_MCLKPERIPH_ID_SERCOM7_APB MCHP_CLOCK_DERIVE_ID(9, 3, 3, 0x3f, 48)
#define CLOCK_MCHP_MCLKPERIPH_ID_TCC4_APB    MCHP_CLOCK_DERIVE_ID(9, 3, 4, 0x3f, 49)
#define CLOCK_MCHP_MCLKPERIPH_ID_TCC5_APB    MCHP_CLOCK_DERIVE_ID(9, 3, 5, 0x3f, 50)
#define CLOCK_MCHP_MCLKPERIPH_ID_TCC6_APB    MCHP_CLOCK_DERIVE_ID(9, 3, 6, 0x3f, 51)
#define CLOCK_MCHP_MCLKPERIPH_ID_TCC7_APB    MCHP_CLOCK_DERIVE_ID(9, 3, 7, 0x3f, 52)
#define CLOCK_MCHP_MCLKPERIPH_ID_ADC_APB     MCHP_CLOCK_DERIVE_ID(9, 3, 8, 0x3f, 53)
#define CLOCK_MCHP_MCLKPERIPH_ID_AC_APB      MCHP_CLOCK_DERIVE_ID(9, 3, 9, 0x3f, 54)
#define CLOCK_MCHP_MCLKPERIPH_ID_PTC_APB     MCHP_CLOCK_DERIVE_ID(9, 3, 10, 0x3f, 55)
#define CLOCK_MCHP_MCLKPERIPH_ID_I2S_APB     MCHP_CLOCK_DERIVE_ID(9, 3, 11, 0x3f, 56)
#define CLOCK_MCHP_MCLKPERIPH_ID_PCC_APB     MCHP_CLOCK_DERIVE_ID(9, 3, 12, 0x3f, 57)
#define CLOCK_MCHP_MCLKPERIPH_ID_CCL_APB     MCHP_CLOCK_DERIVE_ID(9, 3, 13, 0x3f, 58)
#define CLOCK_MCHP_MCLKPERIPH_ID_PDEC_APB    MCHP_CLOCK_DERIVE_ID(9, 3, 14, 0x3f, 59)
#define CLOCK_MCHP_MCLKPERIPH_ID_ETH_APB     MCHP_CLOCK_DERIVE_ID(9, 3, 15, 0x3f, 60)
#define CLOCK_MCHP_MCLKPERIPH_ID_TRNG_APB    MCHP_CLOCK_DERIVE_ID(9, 3, 16, 0x3f, 61)
#define CLOCK_MCHP_MCLKPERIPH_ID_USB_APB     MCHP_CLOCK_DERIVE_ID(9, 3, 17, 0x3f, 62)
#define CLOCK_MCHP_MCLKPERIPH_ID_EBI_APB     MCHP_CLOCK_DERIVE_ID(9, 3, 18, 0x3f, 63)
#define CLOCK_MCHP_MCLKPERIPH_ID_BSDAP_AHB   MCHP_CLOCK_DERIVE_ID(9, 3, 19, 0x3f, 64)
#define CLOCK_MCHP_MCLKPERIPH_ID_MAX         (64)

#endif /* INCLUDE_ZEPHYR_DT_BINDINGS_CLOCK_MCHP_PIC32CK_SG_GC_CLOCK_H_ */
